### ISSUE TITLE
Question - is there documentation that aggregates all API calls, atomicity, etc.

### ISSUE THREAD

**Issue by rabinnh** [chrislusf/weed-fs#113]
We are evaluating Weed and it looks like a project with a bright future.  However I am unable to find thorough documentation of the API.  I see this page: https://code.google.com/p/weed-fs/wiki/HttpAPIs and then I found this page: https://code.google.com/p/weed-fs/wiki/HttpAPIs on a completely different site.  I'm unsure which are valid.

We almost rejected Weed completely because we did not see a "move" verb in the API docs, but checking the code, I see that it has been implemented in filer_embedded.go:

func (filer *FilerEmbedded) Move(fromPath string, toPath string) error {

Also, there is no discussion of atomicity.  For example, what happens if one client is reading and another attempts to move or put, or vice-versa?

**Comment by chrislusf** [comment]
Please check documentation on github. https://github.com/chrislusf/weed-fs/wiki

The move function is implemented for embedded filer only, and with O(1) complexity. The cassandra or redis version do not support move (because it can not be implemented in O(1) for large folders).

There are no transaction. All operations are atomic where the last operation wins.

**Comment by chrislusf** [comment]
I updated the github wiki. Welcome to ask questions if still unclear.
