### ISSUE TITLE
Can I upload variable number of images using same key?

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/weed-fs#98]
Suppose I've got object with variable number of images. User can add/delete images. I want to get single file key for this object and upload multiple images using this key.

I tested upload/delete API. Here is my conclusions:
1. I can upload image with any number - suppose I got `3,01637037d6` key without `count` param. I can upload image with `3,01637037d6_1` key and `3,01637037d6_3` (skipping `3,01637037d6_2`).
2. I can replace any image
3. I can delete any image - I can delete image `3,01637037d6_3` and image `3,01637037d6_1` will still exist.  

 Is it ok? Does weed expect this behavior?

**Comment by chrislusf** [comment]
This works because 3,01637037d6_1 is basically same as the next file id, 3,01637037d6 + 1. So you are using the next file id without telling the master. The next file id could be used by the next "assign" call.

You need to assign with a count, and set the count pretty high, like 20. The operation is pretty cheap.
